/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ClientLogo = {
  _id: string;
  _type: "clientLogo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Equipment = {
  _id: string;
  _type: "equipment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  description: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  specs?: string;
  hotspotX: number;
  hotspotY: number;
  order?: number;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  icon: string;
  deliverables?: Array<string>;
  turnaround?: string;
  order?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clientName: string;
  company: string;
  role?: string;
  quote: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featured?: boolean;
  order?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category:
    | "social-media"
    | "testimonial"
    | "interview"
    | "corporate"
    | "podcast"
    | "photo";
  description?: string;
  youtubeVideoId: string;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featured?: boolean;
  order?: number;
};

export type FounderProfile = {
  _id: string;
  _type: "founderProfile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName: string;
  title: string;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  journey?: Array<{
    year: string;
    title: string;
    description?: string;
    _key: string;
  }>;
  vision?: string;
  motivations?: string;
  skills?: Array<string>;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle: string;
  description: string;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroBackground?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroBackgroundDark?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroBackgroundLit?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroHeadline: string;
  heroSubtitle: string;
  valuePropositions: Array<{
    title: string;
    description: string;
    icon: string;
    statValue?: number;
    statSuffix?: string;
    _key: string;
  }>;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }>;
  ctaText: string;
  ctaUrl: string;
  founderPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  founderBio?: string;
  contactEmail?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Page
  | Slug
  | SanityImageAssetReference
  | ClientLogo
  | SanityImageCrop
  | SanityImageHotspot
  | Equipment
  | Service
  | Testimonial
  | Project
  | FounderProfile
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    siteTitle,    description,    ogImage,    heroBackgroundDark,    heroBackgroundLit,    heroHeadline,    heroSubtitle,    valuePropositions[]{      title,      description,      icon,      statValue,      statSuffix    },    socialLinks[]{      platform,      url    },    ctaText,    ctaUrl,    founderPhoto,    founderBio,    contactEmail  }
export type SITE_SETTINGS_QUERY_RESULT = {
  siteTitle: string;
  description: string;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroBackgroundDark: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  heroBackgroundLit: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  heroHeadline: string;
  heroSubtitle: string;
  valuePropositions: Array<{
    title: string;
    description: string;
    icon: string;
    statValue: number | null;
    statSuffix: string | null;
  }>;
  socialLinks: Array<{
    platform: string | null;
    url: string | null;
  }> | null;
  ctaText: string;
  ctaUrl: string;
  founderPhoto: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  founderBio: string | null;
  contactEmail: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc){    _id,    title,    description,    icon,    deliverables,    turnaround,    order  }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  description: string;
  icon: string;
  deliverables: Array<string> | null;
  turnaround: string | null;
  order: number | null;
}>;

// Source: src/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(order asc){    _id,    title,    slug,    category,    description,    youtubeVideoId,    thumbnail,    featured,    order  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  category:
    | "corporate"
    | "interview"
    | "photo"
    | "podcast"
    | "social-media"
    | "testimonial";
  description: string | null;
  youtubeVideoId: string;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featured: boolean | null;
  order: number | null;
}>;

// Source: src/sanity/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(order asc){    _id,    clientName,    company,    role,    quote,    avatar,    featured,    order  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  clientName: string;
  company: string;
  role: string | null;
  quote: string;
  avatar: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  featured: boolean | null;
  order: number | null;
}>;

// Source: src/sanity/queries.ts
// Variable: CLIENT_LOGOS_QUERY
// Query: *[_type == "clientLogo"] | order(order asc){    _id,    name,    logo,    url,    order  }
export type CLIENT_LOGOS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url: string | null;
  order: number | null;
}>;

// Source: src/sanity/queries.ts
// Variable: EQUIPMENT_QUERY
// Query: *[_type == "equipment"] | order(order asc){    _id,    name,    description,    image,    specs,    hotspotX,    hotspotY,    order  }
export type EQUIPMENT_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  description: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  specs: string | null;
  hotspotX: number;
  hotspotY: number;
  order: number | null;
}>;

// Source: src/sanity/queries.ts
// Variable: FOUNDER_PROFILE_QUERY
// Query: *[_type == "founderProfile"][0]{    fullName,    title,    bio,    photo,    journey[]{      year,      title,      description    },    vision,    motivations,    skills,    socialLinks[]{      platform,      url    }  }
export type FOUNDER_PROFILE_QUERY_RESULT = {
  fullName: string;
  title: string;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  journey: Array<{
    year: string;
    title: string;
    description: string | null;
  }> | null;
  vision: string | null;
  motivations: string | null;
  skills: Array<string> | null;
  socialLinks: Array<{
    platform: string | null;
    url: string | null;
  }> | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    title,    slug,    body  }
export type PAGE_BY_SLUG_QUERY_RESULT = {
  title: string;
  slug: Slug;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0]{\n    siteTitle,\n    description,\n    ogImage,\n    heroBackgroundDark,\n    heroBackgroundLit,\n    heroHeadline,\n    heroSubtitle,\n    valuePropositions[]{\n      title,\n      description,\n      icon,\n      statValue,\n      statSuffix\n    },\n    socialLinks[]{\n      platform,\n      url\n    },\n    ctaText,\n    ctaUrl,\n    founderPhoto,\n    founderBio,\n    contactEmail\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "service"] | order(order asc){\n    _id,\n    title,\n    description,\n    icon,\n    deliverables,\n    turnaround,\n    order\n  }\n': SERVICES_QUERY_RESULT;
    '\n  *[_type == "project"] | order(order asc){\n    _id,\n    title,\n    slug,\n    category,\n    description,\n    youtubeVideoId,\n    thumbnail,\n    featured,\n    order\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "testimonial"] | order(order asc){\n    _id,\n    clientName,\n    company,\n    role,\n    quote,\n    avatar,\n    featured,\n    order\n  }\n': TESTIMONIALS_QUERY_RESULT;
    '\n  *[_type == "clientLogo"] | order(order asc){\n    _id,\n    name,\n    logo,\n    url,\n    order\n  }\n': CLIENT_LOGOS_QUERY_RESULT;
    '\n  *[_type == "equipment"] | order(order asc){\n    _id,\n    name,\n    description,\n    image,\n    specs,\n    hotspotX,\n    hotspotY,\n    order\n  }\n': EQUIPMENT_QUERY_RESULT;
    '\n  *[_type == "founderProfile"][0]{\n    fullName,\n    title,\n    bio,\n    photo,\n    journey[]{\n      year,\n      title,\n      description\n    },\n    vision,\n    motivations,\n    skills,\n    socialLinks[]{\n      platform,\n      url\n    }\n  }\n': FOUNDER_PROFILE_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    title,\n    slug,\n    body\n  }\n': PAGE_BY_SLUG_QUERY_RESULT;
  }
}
